Q: ["q0", "q1", "qloop"]
Σ: ["0", "1"]
Γ: ["0", "1", "_"]
q0: "q0"
qaccept: "qaccept"
qreject: "qreject"
δ:
  "q0":
    "0": [["qloop", "0", "R"]]   # Enters a loop state and continues right
    "1": [["qreject", "1", "R"]]
  "qloop":
    "0": [["q0", "0", "L"]]      # Moves back to q0, creating a loop
    "1": [["qloop", "1", "R"]]
cadena: "0000000"
