Q: ["q0", "q1", "qloop"]
Σ: ["0", "1", "2"]
Γ: ["0", "1", "_"]
q0: "q0"
qaccept: "qaccept"
qreject: "qreject"
δ:
  "q0":
    "0": [["qloop", "0", "R"]]
    "1": [["qaccept", "1", "R"]]
    "2": [["qreject", "2", "R"]]
  "qloop":
    "0": [["q0", "0", "L"]]
    "1": [["q0", "1", "R"]]
cadena: "20000"
description: ""