Q: ["q0", "q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "qaccept", "qreject"]
Σ: ["0", "1"]
Γ: ["0", "1", "_", "Z", "B", "A"]
q0: "q0"
qaccept: "qaccept"
qreject: "qreject"
δ:
  "q0":
    "0": [["q0", "0", "L"]]
    "1": [["q0", "1", "L"]]
    "_": [["q1", "A", "R"]]
  "q1":
    "0": [["q1", "0", "R"]]
    "1": [["q1", "1", "R"]]
    "_": [["q2", "Z", "L"]]
  "q2":
    "_": [["q2", "_", "L"]]
    "A": [["q8", "_", "L"]]
    "1": [["q3", "_", "R"]]
    "0": [["q6", "_", "R"]]
  "q8":
    "_": [["q8", "_", "R"]]
    "Z": [["qaccept", "_", "R"]]
  "q3":
    "_": [["q3", "_", "R"]]
    "Z": [["q4", "Z", "R"]]
  "q4":
    "_": [["q5", "1", "L"]]
    "0": [["q4", "0", "R"]]
    "1": [["q4", "1", "R"]]
  "q5":
    "0": [["q5", "0", "L"]]
    "1": [["q5", "1", "L"]]
    "Z": [["q2", "Z", "L"]]
  "q6":
    "_": [["q6", "_", "R"]]
    "Z": [["q7", "Z", "R"]]
  "q7":
    "_": [["q5", "0", "L"]]
    "0": [["q7", "0", "R"]]
    "1": [["q7", "1", "R"]]
cadena: "101000"
description: "retorna el reverso de la cadena dada compuesta por el caracter '0' o '1'"